name: SplitChat
version: 1.2
api: ["2.0.0"]
author: The Oni
description: ${project.description}
main: theoni.splitchat.Main

permissions:
  splitchat.chat.local:
    default: op
  splitchat.chat.global:
    default: op
  splitchat.command.spy:
    default: op
